INC_DIR=$(src)/include
OBJ_DIR=driver_src

_DEPS = debug.h secvault.h
DEPS = $(patsubst %,$(INC_DIR)/%,$(_DEPS))

_OBJ = main.o ctl.o vault.o
OBJ = $(patsubst %,$(OBJ_DIR)/%,$(_OBJ))

EXTRA_CFLAGS += -I$(INC_DIR)
EXTRA_CFLAGS += -std=gnu99

obj-m += secvault.o
secvault-objs := $(OBJ)

driver:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

.PHONY: clean	